title: Julian Martinez # your name (or website title) here
logo: "images/Dark Green Diamond Edge Tech Computer Logo.png?raw=true"
description:
I am a soon-to-be Software Development graduate from Western Governors University. In combining a rigorous academic experience with professional roles in the public and private sector, I have a verifiable history of professional success as both an intern, student, and worker. Experiential focal points include network configuration, network security, system administration, code testing/debugging, requirements analysis, quality assurance, user interface design, team leadership, and complex problem-solving. 

Currently, I am a Blockchain Developer with Intelligensia. In this role, I coordinate the testing and development of smart contracts, as well as the optimization of their code. I also engage with clients to define their project requirements and establish the structure of the product to be developed.

Colleagues describe me as a progressive, driven, down-to-earth, technical expert who can be relied on to offer superior solutions that deliver the intended results on time and under budget.

I am interested in contacting former colleagues and managers, as well as other professionals in my field. Feel free to contact me through this profile if you wish to connect.

I am pursuing new opportunities and can be reached through this profile, or by email at julian_martinez28@outlook.com

  <br><br>
  <a href="https://www.linkedin.com/in/julian-martinez28/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
